### ISSUE TITLE
Update to v4.2.0?

### ISSUE THREAD

**Issue by chmac** [praneybehl/meteor-react-notification#1]
Any plans to update to v4.2.0 of react-notificatoin?

**Comment by praneybehl** [comment]
Sorry mate, been really busy and with n number of ways to use react and react based plugins I'm about to pull it off. Please feel free to fork the repo and add it to atmosphere.

**Comment by chmac** [comment]
OK, thanks. We started using it, so happy to publish a version on atmosphere.

**Comment by chmac** [comment]
I published a fork [here](https://atmospherejs.com/superlumen/react-notification).
